### ISSUE TITLE
Rest基础命令 － Friends

### ISSUE THREAD

**Issue by guitarpoet** [PinetTech/RestXMPP#10]
由于服务器端有可能要查看好友情况，所以需要提供这个功能，可以通过 /control/friends的HTTP GET请求来访问，可以使用的参数有：

status（可选）：列出所有符合该状态的好友，如果不选，则列出所有好友，状态有（online、offline两种）

**Comment by spartacus429496** [comment]
列举好友及其状态功能已经完成。
结果如：

[group]:pinet
------------------------------------------------------------------------

[jid]:              victor@pinet.cc
[status]:           online
[subscription]:     both

[jid]:              user1@pinet.cc
[status]:           offline
[subscription]:     both
