### ISSUE TITLE
Rest基础命令 － Status

### ISSUE THREAD

**Issue by guitarpoet** [PinetTech/RestXMPP#5]
可以通过访问 /control/status 来查看服务器当前运行的状态，状态信息有：

1. 服务绑定Host
2. 服务绑定Port
3. 登录状态
4. 登录jid
5. XMPP Server相关信息（server，port）
6. 运行时间

其他的信息可以酌情添加（如发送了多少条消息，收到了多少条消息，执行了多少命令）。

调用示例：

     curl http://localhost:8080/control/status

**Comment by kallun** [comment]
基本的状态信息显示已经完成
