### ISSUE TITLE
Rest基础命令 － Message

### ISSUE THREAD

**Issue by guitarpoet** [PinetTech/RestXMPP#7]
此功能为最核心功能之一。可以通过向 /control/message 发出GET或者POST请求来发送消息。

请求参数均为必填，如果没有，则调用失败。请求参数说明如下：

1. jid：发送对象的jid
2. message：发送给对象的消息

调用示例

    curl -XPOST -Fjid=jack@pinet.cc -Fmessage="Hello world" http://localhost:8080/xmpp/message

**Comment by kallun** [comment]
这个功能已经验证可用。
