### ISSUE TITLE
XMPP基础功能 － 自动添加好友

### ISSUE THREAD

**Issue by guitarpoet** [PinetTech/RestXMPP#9]
由于服务器端要了解所有的盒子的运行情况，所以，必须要能够自动同意并添加好友。

此部分需要的配置内容有：

1. friend_pattern：好友jid必须遵循的pattern，否则不添加
2. friend_default_group：好友的请求信息就是应该添加好友的组，如果没有，则用此默认配置

此部分为自动功能，无需调用。

**Comment by spartacus429496** [comment]
该功能已经完成，friend_pattern和friend_default_group的配置，在默认配置文件中。
